# vi: set ft=ruby :

GUEST_NAME  = Dir.pwd.split('/').last
HOST_NAME   = ENV['SYSNAME'] || 'localhost'
FULL_NAME   = "#{GUEST_NAME}.#{HOST_NAME}".freeze
KEYFILE     = File.expand_path('~/.ssh/id_rsa.pub')
KEYTEXT     = File.exist?(KEYFILE) ? File.read(KEYFILE) : ''
ANS_BASE    = "/iac/ansible_base/ANS/VVM".freeze
SCRIPT_FILE = "#{ANS_BASE}/bin/bootstrap.bash".freeze

# find the network device by running `ifconfig` on your host
NETWORK_DEVICE = "enp114s0".freeze 

Vagrant.configure('2') do |config|
  config.vm.box = 'generic/ubuntu2204'
  config.vm.synced_folder '.',                  '/iac/config',       owner: 'vagrant', group: 'vagrant'
  config.vm.synced_folder '~/iac/ansible_base', '/iac/ansible_base', owner: 'vagrant', group: 'vagrant'

  config.vm.network 'public_network', bridge: NETWORK_DEVICE,
    use_dhcp_assigned_default_route: true

  config.vm.define FULL_NAME do |guest|
    guest.vm.hostname = FULL_NAME
    guest.ssh.insert_key = false
  end

  config.vm.network 'forwarded_port', guest: 22, host: 2240,
    ip: 'ssh', auto_correct: true

  config.vm.provider 'virtualbox' do |v|
    v.memory = 2048
    v.cpus   = 2
  end

  # copy the user's ssh pubkey to the guest at /tmp/hostkey.pub
  # the hostkey is used in the ansible provisioning step
  config.vm.provision 'shell', inline: <<-SHELL
    # export NOANSIBLE=true
    source #{SCRIPT_FILE}
    writekey "#{KEYTEXT}"
  SHELL
  
  config.vm.provision 'ansible_local' do |ansible|
    ansible.install = false
    ansible.provisioning_path = '/iac/ansible_base/ANS/VVM'
    ansible.playbook = 'playbooks/raw_full.yml'
  end
end
