#vi: set ft=ruby :

GUEST_NAME = Dir.pwd.split('/').last
HOST_NAME  = ENV["SYSNAME"] || "localhost"
FULL_NAME  = GUEST_NAME + '.' + HOST_NAME
KEYFILE    = File.expand_path("~/.ssh/id_rsa.pub")
KEYTEXT    = File.exist?(KEYFILE) ? File.read(KEYFILE) : ""
SCRIPT_URL = "raw.github.com/andyl/x-ansible/master/bin/bootstrap.bash"

Vagrant.configure("2") do |config|
  config.vm.box = "bugmark/packaged_full"
  config.vm.synced_folder ".", "/vagrant", owner: "vagrant"

  config.vm.network "public_network", bridge: "eno1", 
    use_dhcp_assigned_default_route: true
  
  config.vm.define FULL_NAME do |guest|
    guest.vm.hostname = FULL_NAME
    guest.ssh.insert_key = false
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   source <(curl -sL #{BOOTSTRAP_URL})
  # SHELL

  # config.vm.provision "ansible_local" do |ansible|
  #   ansible.install = false
  #   ansible.provisioning_path = "/vagrant/ANSIBLE"
  #   ansible.playbook = "playbooks/raw_base.yml"
  # end
end
