#vi: set ft=ruby :

HOST_NAME     = ENV["SYSNAME"]
GUEST_NAME    = Dir.pwd.split('/').last
BOOTSTRAP_URL = "https://git.io/fp53p" 

def full_name
  GUEST_NAME + '.' + HOST_NAME
end

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.synced_folder ".", "/vagrant", owner: "vagrant"

  config.vm.network "public_network", bridge: "eno1", 
    use_dhcp_assigned_default_route: true
  
  config.vm.define full_name do |guest|
    guest.vm.hostname = full_name
    guest.ssh.insert_key = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    source <(curl -sL #{BOOTSTRAP_URL})
  SHELL

  config.vm.provision "ansible_local" do |ansible|
    ansible.install = false
    ansible.provisioning_path = "/vagrant/ANSIBLE"
    ansible.playbook = "playbooks/base.yml"
  end
end
