# vi: set ft=ruby :

HOST = ENV["SYSNAME"]
NAME = Dir.pwd.split('/').last

def full_name
  NAME + '.' + HOST
end

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  config.vm.network "public_network", bridge: "eno1", 
    use_dhcp_assigned_default_route: true
  
  config.vm.define full_name do |guest|
    guest.vm.hostname = full_name
    guest.ssh.insert_key = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -yq ssh python
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
