# vi: set ft=ruby :

HOST = ENV["SYSNAME"]

def full_name(text)
  text + '.' + HOST
end

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  config.vm.network "public_network", bridge: "eno1", 
    use_dhcp_assigned_default_route: true
  
  config.vm.define HOST do |base|
    base.vm.hostname = full_name("base")
    base.ssh.insert_key = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt update
    apt install -yq ssh python
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
